
test:
	$(info Running harvest tests)
	./bats/bin/bats .

clean:
	$(info Cleaning up test files)
	@rm -rf harvest harvested
	@rm -rf /tmp/harvest_test
	@rm -rf bob_dylan bob_marley herzog nice_books zenroom
